[package]
name = "sicp-rust"
version = "0.1.0"
authors = ["zcheng"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
recur-fn = "2.2"

[dependencies.num]
version = "0.3"
default-features = true 